opencost:
  fullname: opencost
  exporter:
    name: opencost
    # The GCP Pricing API requires a key. This is supplied just for evaluation.
    cloudProviderApiKey: "AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U"
    # Default cluster ID to use if cluster_id is not set in Prometheus metrics.
    defaultClusterId: "default-cluster"
    image:
      repository: quay.io/kubecost1/kubecost-cost-model
      tag: latest
    resources:
      requests:
        cpu: "10m"
        memory: "55M"
      limits:
        cpu: "999m"
        memory: "1G"

  namespace:
    create: true
    name: opencost

  prometheus:
    serviceName: my-prometheus
    namespaceName: opencost

  ui:
    enabled: true
    image:
      repository: quay.io/kubecost1/opencost-ui
      tag: latest
    resources:
      requests:
        cpu: "10m"
        memory: "55M"
      limits:
        cpu: "999m"
        memory: "1G"

  tolerations: []
